[package]
name = "websocket-tungstenite-retry"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/grooviegermanikus/websocket-tungstenite-retry"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "^2.3.1"
anyhow = "^1.0"
futures = "^0.3.21"
log = "^0.4.0"
serde = { version = "^1.0.141", features = ["derive"] }
serde_json = "^1.0.82"
tokio = { version = "^1.14.1", features = ["rt-multi-thread", "time", "macros", "sync", "io-util"] }
tokio-tungstenite = { version = "^0.17.2", features = ["native-tls"] }

[dev-dependencies]
hyper = "0.14.20"
tower-http = { version = "0.4.0", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
env_logger = "^0.8.4"
jsonrpsee = { version = "^0.18.1", features = ["http-client", "macros"] }
tracing = "0.1.34"
tracing-test = "0.2.4"

